services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_ATLAS_CONNECTION: mongodb://mongodb:27017/todoapp
      PORT: 5000
    depends_on:
      - mongodb
    command: sh -c "while ! nc -z mongodb 27017; do echo 'waiting for mongodb...'; sleep 2; done; npm start"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:80"  # ← CHANGEMENT ICI : 3001 au lieu de 3000
    depends_on:
      - backend
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8082:8080"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: unless-stopped

volumes:
  mongodb_data:
  jenkins_home:
